version: '3'
services:
  website.student_list:
   image: php:apache
   container_name: website.student_list
   depends_on:
     - api
   ports:
     - "8000:80"
   volumes:
     - ./website/:/var/www/html
   environment:
     - USERNAME=toto
     - PASSWORD=python
   networks:
     - student_list.network
  api:
   image: api:v1
   container_name: api
   volumes:
     - ./simple_api:/data
   ports:
     - "5000:5000"
   networks:
     - student_list.network
networks:
    student_list.network:
